# Comment Internet fonctionne ?

Dans cet ouvrage, nous souhaitons expliquer en détail comment fonctionnent le web.
De l'ouverture de votre navigateur de prédilection à la consultation de la page, nous allons présenter, en détails, les différentes étapes qui s'exécutent pendant ces quelques millisecondes.

Nous allons partir d'une application d'exemple composé d'une API REST développé avec Express.js et d'une application web développée avec 11ty, servie par NGINX.
Nous allons également prendre le navigateur Firefox comme navigateur utilisé pendant notre expérimentation.

Durant la première partie de cette ouvrage, nous allons récupérer les codes sources de Firefox, NGINX et Node.js afin de pouvoir regarder et tester le code pensant nos expérimentations.
Nous lancerons ensuite notre application.

## Présentation de l'application file rouge

Afin de répondre à la problématique de cet ouvrage, nous allons utiliser une application assez simle. Celle-ci
sera une application statique dévelopée avec Eleventy, servie par Nginx, et une API développée sur Node.js

include::chapters/setup/index.adoc[]

## DNS

Il y plusieurs cache DNS lorsque nous naviguons sur le net, afin de limiter le nombre de résolution nécessaire. Le premier cache
que nous pouvons mentionner est le cache de votre ordinateur.

## HTTP

Voici un exemple de message HTTP. Nous avons sur la première ligne le verbe HTTP, l'URI ainsi que la version du protocole HTTP.
Puis, nous avons une succession de métadonnées, appelées en-tetes.

[source]
----
GET /hello.htm HTTP/1.1
User-Agent: Mozilla/4.0 (compatible; MSIE5.01; Windows NT)
Host: www.tutorialspoint.com
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
----

Ci-dessous, vous trouverez la liste des verbes HTTP que nous pouvons utiliser .

* GET
* POST
* POST
* PUT
* OPTIONS
* DELETE
* PATCH
* TRACE
* CONNECT

### HTTPS

### HTTP2

### HTTP3

## CSP

Le terme CSP signifie Content Security Policy. C'est un mécanisme permettant de définir si un site Web, hébergé sur un
certain, est capable ou non de faire des requetes HTTP vers un autre service hébergé sur un autre nom de domain, afin
de récupérer un ressource (au sens REST, ou une simple ressource statique).

Si cette contrainte n'est pas respectée, la requete HTTP sera en erreur, et vous obtiendrez une erreur similaire à la suivante :

[source]
----
Error: Access to fetch at 'https://external-api.com' from origin 'chrome-extension://bunchofchars' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
----

## Parsing

### DOM

### CSSOM

### Accessibility Tree

## Ressources Statiques

### JavaScript

### CSS

### Images

### Defer, async, ...

## Paint

## CORS
