# Comment Internet fonctionne ?

Dans cet ouvrage, nous souhaitons expliquer en détail comment fonctionnent le web.
De l'ouverture de votre navigateur de prédilection à la consultation de la page, nous allons présenter, en détails, les différentes étapes qui s'exécutent pendant ces quelques millisecondes.

Nous allons partir d'une application d'exemple composé d'une API REST développé avec Express.js et d'une application web développée avec 11ty, servie par NGINX.
Nous allons également prendre le navigateur Firefox comme navigateur utilisé pendant notre expérimentation.

Durant la première partie de cette ouvrage, nous allons récupérer les codes sources de Firefox, NGINX et Node.js afin de pouvoir regarder et tester le code pensant nos expérimentations.
Nous lancerons ensuite notre application.

## Présentation de l'application file rouge

Afin de répondre à la problématique de cet ouvrage, nous allons utiliser une application assez simle. Celle-ci
sera une application statique dévelopée avec Eleventy, servie par Nginx, et une API développée sur Node.js

## Installation des différentes briques

Afin de vraiment bien comprendre le fonctionnement d'internet, nous allons à présent télécharger, installer et
lancer localement un navigateur, NGinx et la plateforme Node.js. Le fait de lancer ces trois briques depuis
le code source, nous permettra d'y jeter un coup d'oeil et d'entrer dans leurs entrailles.

### Node.js

Node.js sera la plateforme qui exécutera une API REST que nous développerons avec le langage Typescript.

### Nginx

NGinx hebergera notre application statique dévelopée via Eleventy.

### Firefox

### Applications

Nous allons à présent récupérer, installer et lancer l'application utilisée tout au long de cette ouvrage.

## DNS

Il y plusieurs cache DNS lorsque nous naviguons sur le net, afin de limiter le nombre de résolution nécessaire. Le premier cache
que nous pouvons mentionner est le cache de votre ordinateur.

## HTTP

## CSP

Le terme CSP signifie Content Security Policy. C'est un mécanisme permettant de définir si un site Web, hébergé sur un
certain, est capable ou non de faire des requetes HTTP vers un autre service hébergé sur un autre nom de domain, afin
de récupérer un ressource (au sens REST, ou une simple ressource statique).

Si cette contrainte n'est pas respectée, la requete HTTP sera en erreur, et vous obtiendrez une erreur similaire à la suivante :

[source]
----
Error: Access to fetch at 'https://external-api.com' from origin 'chrome-extension://bunchofchars' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
----



## Parsing

## Ressources Statiques

## Paint

## CORS
